# Generated by Django 3.2.15 on 2022-09-30 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('plantId', models.IntegerField(primary_key=True, serialize=False)),
                ('plantName', models.CharField(max_length=50)),
                ('detailPictureUrl', models.CharField(max_length=500)),
                ('plantDescription', models.TextField()),
                ('season', models.CharField(blank=True, max_length=50, null=True)),
                ('classification', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Collect',
            fields=[
                ('collectId', models.AutoField(primary_key=True, serialize=False)),
                ('collectPictureUrl', models.CharField(max_length=500)),
                ('collectDate', models.DateField(auto_now_add=True)),
                ('collectTitle', models.CharField(max_length=100)),
                ('collectContent', models.TextField()),
                ('collectPlace', models.CharField(max_length=50)),
                ('locationId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection', to='locations.location')),
                ('plantId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection', to='plantbook.plant')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection', to='accounts.user')),
            ],
        ),
    ]
