# Generated by Django 3.2.15 on 2022-09-30 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('locationId', models.AutoField(primary_key=True, serialize=False)),
                ('areaId', models.IntegerField()),
                ('areaName', models.CharField(max_length=50)),
                ('sigunguId', models.IntegerField()),
                ('sigunguName', models.CharField(max_length=50)),
            ],
        ),
    ]
