# Generated by Django 3.2.15 on 2022-09-30 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Title',
            fields=[
                ('titleId', models.AutoField(primary_key=True, serialize=False)),
                ('titleName', models.CharField(max_length=50)),
                ('titleDescription', models.CharField(max_length=200)),
                ('titlePictureUrl', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Obtained',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isRep', models.BooleanField(default=False)),
                ('titleId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='titles.title')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='obtained', to='accounts.user')),
            ],
        ),
    ]
